homeassistant:
# Name of the location where Home Assistant is running
  name: Home

# get lat/long from http://www.latlong.net/convert-address-to-lat-long.html
  latitude: !secret config_latitude
  longitude: !secret config_longitude

# Impacts weather/sunrise data (altitude above sea level) 
  elevation: 508

# C for Celsius, F for Fahrenheit
  unit_system: metric

# Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Zurich

  customize: !include customization.yaml

# Allows you to issue voice commands from the frontend
conversation:

device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.1.1/24
    home_interval: 10
    exclude:
     - 192.168.1.7

# Discover some devices automatically
discovery:

# Enables the frontend
frontend:

# Enables support for tracking state changes over time.
history:
  exclude:
    domains:
      - sun
      - weblink
      - updater
    entities:
      - sensor.date
      - sensor.time
      - sensor.next_departure
      - sensor.music_title
      - sensor.music_artist
      - switch.music_playpause
      - camera.garage_dcs820l
      - camera.wetter_alarm_schweiz
      - camera.wetter_schweiz
      - camera.wetter_alarm_europa
      - sensor.since_last_boot
      - sensor.last_boot
      - sensor.cpu_use
      - sensor.cpu_speed
      - sensor.disk_use
      - sensor.received_wlan1
      - sensor.sent_wlan1

# View all events in a logbook
logbook:
  exclude:
    entities:
      - sensor.date
      - sensor.time
      - sensor.next_departure
      - sensor.cpu_speed
      - sensor.music_title
      - sensor.music_artist
      - sensor.since_last_boot
    domains:
      - sun
      - weblink

# log and debug homeassistant
logger:
  default: critical
  logs:
    homeassistant.components: debug

# Track the sun
sun:

# Checks for available updates
updater:
  reporting: false

automation: !include_dir_merge_list automation
camera: !include cameras.yaml
switch: !include switches.yaml
sensor: !include sensors.yaml
group: !include groups.yaml

