homeassistant:
# Name of the location where Home Assistant is running
  name: Home

# get lat/long from http://www.latlong.net/convert-address-to-lat-long.html
  latitude:    !secret config_latitude
  longitude:   !secret config_longitude

# Impacts weather/sunrise data (altitude above sea level) 
  elevation: 508

# C for Celsius, F for Fahrenheit
  unit_system: metric

# Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Zurich

  customize:   !include customization.yaml

# Allows you to issue voice commands from the frontend
conversation:

device_tracker:
  - platform: nmap_tracker
    # scan only from 192.168.1.1 to 192.168.1.30
    hosts: 192.168.1.1/27
    home_interval: 10
    exclude:
     - 192.168.1.7

# Discover some devices automatically
discovery:

# Enables the frontend
frontend:

# Enables support for tracking state changes over time.
history:       !include history.yaml

# View all events in a logbook
logbook:       !include logbook.yaml

# log and debug homeassistant
logger:
#  default: critical
  default: debug

# Track the sun
sun:

# Checks for available updates
updater:
  reporting: false

automation:    !include_dir_merge_list automation
camera:        !include cameras.yaml
cover:         !include covers.yaml
sensor:        !include sensors.yaml
shell_command: !include shell_commands.yaml
switch:        !include switches.yaml
group:         !include groups.yaml
input_select:  !include selects.yaml
input_slider:  !include sliders.yaml

