- platform: cpuspeed

- platform: command_line
  command: "/home/mgafner/bin/homewizard.sh -t -d Studio"
  name: Studio Temperature
  unit_of_measurement: "°C"

- platform: command_line
  command: "/home/mgafner/bin/homewizard.sh -t -d James"
  name: James Temperature
  unit_of_measurement: "°C"

- platform: command_line
  command: "/home/mgafner/bin/homewizard.sh -t -d Bad"
  name: Bad Temperature
  unit_of_measurement: "°C"

- platform: command_line
  command: "/home/mgafner/bin/homewizard.sh -h -d Studio"
  name: Studio Humidity
  unit_of_measurement: "%"

- platform: command_line
  command: "/home/mgafner/bin/homewizard.sh -h -d James"
  name: James Humidity
  unit_of_measurement: "%"

- platform: command_line
  command: "/home/mgafner/bin/homewizard.sh -h -d Bad"
  name: Bad Humidity
  unit_of_measurement: "%"

- platform: swiss_public_transport
  from: Bern, Monbijoubr
  to: Bern, Eigerp
# help: https://home-assistant.io/components/sensor.swiss_public_transport/

- platform: time_date
  display_options:
    - 'date'
    - 'time'

- platform: template
  sensors:
    aarelevel:
      value_template: '{{ states.sensor.water_temperature.attributes.level }}'
      friendly_name: 'Aare Level'
      unit_of_measurement: 'm'
    aaredischarge:
      value_template: '{{ states.sensor.water_temperature.attributes.discharge }}'
      friendly_name: 'Aare Discharge'
      unit_of_measurement: 'm3/s'
    template_diff_humidity:
      value_template: '{{ states.sensor.bad_humidity.state - states.sensor.studio_humidity.state }}'
      friendly_name: 'Bath High Humidity'
      unit_of_measurement: '%'

- platform: swiss_hydrological_data
  station: 2135

- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: disk_free
      arg: /
    - type: processor_use
    - type: network_in
      arg: wlan1
    - type: network_out
      arg: wlan1
    - type: last_boot
    - type: since_last_boot

