
- platform: command_line
  command: "~/bin/hass --version"
  name: Homeassistant Version Local
  unit_of_measurement: ""

- platform: command_line
  command: python3 -c "import requests; print(requests.get('https://pypi.python.org/pypi/homeassistant/json').json()['info']['version'])"
  name: Homeassistant Version Newest
  unit_of_measurement: ""

- platform: time_date
  display_options:
    - 'date'
    - 'time'

- platform: template
  sensors:
    internet_roundtrip:
      value_template: '{{ states.binary_sensor.internet.attributes.round_trip_time_avg }}'
      friendly_name: 'Internet Roundtrip'
      unit_of_measurement: 'ms'

- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: disk_free
      arg: /
    - type: processor_use
    - type: network_in
      arg: wlan1
    - type: network_out
      arg: wlan1
    - type: last_boot
    - type: since_last_boot

