- platform: command_line
  switches:
    garage:
      command_on: "/home/mgafner/bin/homewizard.sh -d Garage -s on"
      command_off: "/home/mgafner/bin/homewizard.sh -d Garage -s off"
      command_state: "/home/mgafner/bin/homewizard.sh -d Garage -g"
      value_template: '{{ value == "on" }}'
      friendly_name: Garage
    signal:
      command_on:    "/home/mgafner/bin/homewizard.sh -d Signal -s on"
      command_off:   "/home/mgafner/bin/homewizard.sh -d Signal -s off"
      command_state: "/home/mgafner/bin/homewizard.sh -d Signal -g"
      value_template: '{{ value == "on" }}'
      friendly_name: Signal
    flur:
      command_on:    "/home/mgafner/bin/homewizard.sh -d Flur -s on"
      command_off:   "/home/mgafner/bin/homewizard.sh -d Flur -s off"
      command_state: "/home/mgafner/bin/homewizard.sh -d Flur -g"
      value_template: '{{ value == "on" }}'
      friendly_name: Flur
    bad_licht:
      command_on:    "/home/mgafner/bin/homewizard.sh -d BadLicht -s on"
      command_off:   "/home/mgafner/bin/homewizard.sh -d BadLicht -s off"
      command_state: "/home/mgafner/bin/homewizard.sh -d BadLicht -g"
      value_template: '{{ value == "on" }}'
      friendly_name: Bad Licht
    bad_heizung:
      command_on:    "/home/mgafner/bin/homewizard.sh -d BadHeizung -s on"
      command_off:   "/home/mgafner/bin/homewizard.sh -d BadHeizung -s off"
      command_state: "/home/mgafner/bin/homewizard.sh -d BadHeizung -g"
      value_template: '{{ value == "on" }}'
      friendly_name: Bad Heizung
    bad_strahler:
      command_on:    "/home/mgafner/bin/homewizard.sh -d BadStrahler -s on"
      command_off:   "/home/mgafner/bin/homewizard.sh -d BadStrahler -s off"
      command_state: "/home/mgafner/bin/homewizard.sh -d BadStrahler -g"
      value_template: '{{ value == "on" }}'
      friendly_name: Bad Strahler
    bad_luefter:
      command_on:    "/home/mgafner/bin/homewizard.sh -d BadLuefter -s on"
      command_off:   "/home/mgafner/bin/homewizard.sh -d BadLuefter -s off"
      command_state: "/home/mgafner/bin/homewizard.sh -d BadLuefter -g"
      value_template: '{{ value == "on" }}'
      friendly_name: Bad Lüfter
    studio_vorne:
      command_on:    "/home/mgafner/bin/homewizard.sh -d StudioVorne -s on"
      command_off:   "/home/mgafner/bin/homewizard.sh -d StudioVorne -s off"
      command_state: "/home/mgafner/bin/homewizard.sh -d StudioVorne -g"
      value_template: '{{ value == "on" }}'
      friendly_name: Studio vorne
    studio_sonne:
      command_on:    "/home/mgafner/bin/homewizard.sh -d StudioSonne -s on"
      command_off:   "/home/mgafner/bin/homewizard.sh -d StudioSonne -s off"
      command_state: "/home/mgafner/bin/homewizard.sh -d StudioSonne -g"
      value_template: '{{ value == "on" }}'
      friendly_name: Studio Sonne
    studio_hinten:
      command_on:    "/home/mgafner/bin/homewizard.sh -d StudioHinten -s on"
      command_off:   "/home/mgafner/bin/homewizard.sh -d StudioHinten -s off"
      command_state: "/home/mgafner/bin/homewizard.sh -d StudioHinten -g"
      value_template: '{{ value == "on" }}'
      friendly_name: Studio hinten
    studio_heizung:
      command_on:    "/home/mgafner/bin/homewizard.sh -d StudioHeizung -s on"
      command_off:   "/home/mgafner/bin/homewizard.sh -d StudioHeizung -s off"
      command_state: "/home/mgafner/bin/homewizard.sh -d StudioHeizung -g"
      value_template: '{{ value == "on" }}'
      friendly_name: Studio Heizung
    lautsprecher:
      command_on:    "/home/mgafner/bin/homewizard.sh -d Lautsprecher -s on"
      command_off:   "/home/mgafner/bin/homewizard.sh -d Lautsprecher -s off"
      command_state: "/home/mgafner/bin/homewizard.sh -d Lautsprecher -g"
      value_template: '{{ value == "on" }}'
      friendly_name: Amp & Speaker
    music_playpause:
      command_on:    "/home/mgafner/bin/clementine-remote-bash.sh -c play"
      command_off:   "/home/mgafner/bin/clementine-remote-bash.sh -c pause"
      command_state: "/home/mgafner/bin/clementine-remote-bash.sh -g status"
      value_template: '{{ value == "Playing" }}'
      friendly_name: Play/Plause

