- platform: command_line
  switches:
    music_playpause:
      command_on:    "/home/mgafner/bin/mpd-remote-bash.sh -c play"
      command_off:   "/home/mgafner/bin/mpd-remote-bash.sh -c pause"
      command_state: "/home/mgafner/bin/mpd-remote-bash.sh -g status"
      value_template: '{{ value == "play" }}'
      friendly_name: Play/Plause

