# This file is part of home-assistant-config
# https://github.com/mgafner/home-assistant-config
#
# This is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this file.  If not, see <http://www.gnu.org/licenses/>.

resources:
  - type: js
    url: /local/custom-lovelace/entity-attributes-card.js?v=2
  - type: js
    url: /local/custom-lovelace/monster-card.js?v=2
title: Home
views:
  - badges:
      - sensor.moonphase
      - sensor.time
      - sun.sun
    cards:
      - entities:
          - entity: sensor.aare_bern_temperatur
          - entity: sensor.aare_bern_pegelstand
          - entity: sensor.thunersee_spiez_temperatur
          - entity: sensor.thunersee_spiez_pegelstand
          - entity: sensor.thunersee_spiez_gefahrenstufe
          - entity: weblink.thunersee_spiez_infos
        show_header_toggle: false
        title: Outside
        type: entities
    icon: 'mdi:home'
    path: default_view
    title: default_view
  - badges: []
    cards:
      - entity: media_player.room1_tv
        type: media-control
      - entity: media_player.room2_tv
        type: media-control
      - entity: media_player.room2_kodi
        type: media-control
      - entity: media_player.room4_tv
        type: media-control
    icon: 'mdi:music'
    path: media
    title: media
  - badges: []
    cards:
      - entities:
          - entity: sensor.dark_sky_summary
          - entity: sensor.dark_sky_humidity
          - entity: sensor.dark_sky_temperature
        show_header_toggle: false
        title: Wetter Bern Heute
        type: entities
      - entity: camera.wetter_schweiz
        show_header_toggle: false
        title: camera_schweiz
        type: picture-entity
      - entities:
          - entity: sensor.dark_sky_summary_1
          - entity: sensor.dark_sky_humidity_1
        show_header_toggle: false
        title: Wetter Bern Morgen
        type: entities
      - entity: camera.wetter_alarm_schweiz
        show_header_toggle: false
        title: camera_alarm_schweiz
        type: picture-entity
      - entity: camera.wetter_alarm_europa
        show_header_toggle: false
        title: camera_alarm_europa
        type: picture-entity
    icon: 'mdi:weather-partlycloudy'
    path: weather
    title: weather
  - badges: []
    cards:
      - entities:
          - vacuum.robbie
        show_header_toggle: false
        title: Cleaning
        type: entities
      - entities:
          - entity: device_tracker.entry_gateway_homewizard
        show_header_toggle: false
        title: System
        type: entities
    icon: 'mdi:transit-transfer'
    path: entry
    title: Entry
  - badges: []
    cards: []
    icon: 'mdi:pot-mix'
    path: kitchen
    title: Kitchen
  - badges: []
    cards:
      - entities:
          - entity: sensor.room1_thermometer
        show_header_toggle: false
        title: Room 1
        type: entities
      - entity: media_player.room1_tv
        type: media-control
    icon: 'mdi:numeric-1-box-outline'
    path: room1
    title: Room 1
  - badges: []
    cards:
      - type: entities
        entities:
          - entity: sensor.room2_thermometer
        show_header_toggle: false
      - entity: media_player.room2_tv
        type: media-control
      - entity: media_player.room2_kodi
        type: media-control
    icon: 'mdi:numeric-2-box-outline'
    path: room2
    title: Room 2
  - badges: []
    cards: []
    icon: 'mdi:numeric-3-box-outline'
    path: room3
    title: Room 3
  - badges: []
    cards:
      - entities:
          - entity: sensor.room4_thermometer
          - entity: script.room4_light_toggle
          - entity: light.room4_door
          - entity: light.room4_desk
          - entity: light.room4_sun
          - entity: light.room4_bed
          - entity: scene.room4_light_ceiling
          - entity: scene.room4_venti_low
          - entity: scene.room4_venti_mlow
          - entity: scene.room4_venti_medium
          - entity: scene.room4_venti_high
          - entity: scene.room4_venti_off
          - entity: script.room4_light_toggle
        show_header_toggle: false
        title: Room 4
        type: entities
      - entity: media_player.room4_tv
        type: media-control
      - entities:
          - input_boolean.weekday_sunrise
          - sensor.weekday_alarm_time
          - input_number.weekday_alarm_hour
          - input_number.weekday_alarm_minutes
          - script.sunrise
        show_header_toggle: false
        title: Weekday Alarm Clock
        type: entities
      - entity: media_player.room4_kodi
        type: media-control
      - entities:
          - entity: input_boolean.weekend_sunrise
          - entity: sensor.weekend_alarm_time
          - entity: input_number.weekend_alarm_hour
          - entity: input_number.weekend_alarm_minutes
          - entity: script.sunset
        show_header_toggle: false
        title: Weekend Alarm Clock
        type: entities
      - entity: media_player.snapcast_client_a0_c9_a0_94_1b_e2_2
        type: media-control
      - entity: media_player.snapcast_client_b8_27_eb_14_4b_cc
        type: media-control
    icon: 'mdi:numeric-4-box-outline'
    path: room4
    title: Room 4
  - badges: []
    cards: []
    icon: 'mdi:numeric-5-box-outline'
    path: room5
    title: Room 5
  - badges: []
    cards:
      - type: entities
        entities:
          - entity: sensor.room6_thermometer
        show_header_toggle: false
    icon: 'mdi:numeric-6-box-outline'
    path: room6
    title: Room 6
  - badges: []
    cards:
      - entities:
          - entity: sensor.shower_door
          - entity: switch.sonoff_shower_power
          - entity: sensor.sonoff_shower_temperature
          - entity: sensor.shower_temperature_stats_mean
          - entity: sensor.sonoff_shower_humidity
          - entity: sensor.shower_humidity_stats_mean
        show_header_toggle: false
        title: Shower
        type: entities
      - entities:
          - entity: binary_sensor.shower_heating
          - entity: binary_sensor.shower_ventillator
          - entity: automation.shower_showering_detected
          - entity: automation.shower_showering_finished
        show_header_toggle: false
        title: Shower Automations
        type: entities
      - entity: media_player.shower_music
        type: media-control
      - entities:
          - entity: device_tracker.shower_raspi
            secondary_info: last-changed
          - entity: device_tracker.shower_sonoff
            secondary_info: last-changed
        show_header_toggle: false
        title: Shower States
        type: entities
    icon: 'mdi:shower-head'
    path: shower
    title: Shower
  - badges: []
    cards:
      - entities:
          - entity: sensor.bath_door
          - entity: switch.sonoff_bath_power
          - entity: sensor.sonoff_bath_temperature
          - entity: sensor.bath_temperature_stats_mean
          - entity: sensor.sonoff_bath_humidity
          - entity: sensor.bath_humidity_stats_mean
        show_header_toggle: false
        title: Bath
        type: entities
      - entities:
          - entity: device_tracker.bath_raspi
          - entity: device_tracker.bath_sonoff
        show_header_toggle: false
        title: Bath States
        type: entities
      - entity: media_player.bath_music
        type: media-control
    icon: 'mdi:shower'
    path: bath
    title: Bath
  - badges: []
    cards:
      - entities:
          - sensor.level0_ip_count
          - sensor.level0_phone_hugo_last_home
          - sensor.level0_phone_ruth_last_home
          - sensor.level0_tablet_ruth_last_home
        show_header_toggle: false
        title: Status
        type: entities
    icon: 'mdi:numeric-0-box-multiple-outline'
    path: level0
    title: Level 0
  - badges: []
    cards: []
    icon: 'mdi:arrow-down-bold-box-outline'
    path: basement
    title: Basement
  - badges: []
    cards: []
    icon: 'mdi:car'
    path: car
    title: Car
  - badges: []
    cards: []
    icon: 'mdi:home-minus'
    path: studio
    title: Studio Sandrain
  - badges: []
    cards: []
    icon: 'mdi:puzzle'
    path: puzzle
    title: Puzzle
  - badges: []
    cards:
      - entities:
          - entity: script.sunset
          - entity: script.sunrise
          - entity: input_boolean.script_sun_running
        title: Scripts
        type: entities
      - card:
          entities:
            - entity: automation.bath_music_pause
            - entity: automation.bath_music_play
            - entity: automation.example_with_persistent_notification
            - entity: automation.level0_enter_home_notification
            - entity: automation.level0_leave_home_notification
            - entity: automation.level0_no_connection_notification
            - entity: automation.neala_enter_home_notification
            - entity: automation.neala_leave_home_notification
            - entity: automation.room4_hue_lights_time_of_day_brightness_switch_on
            - entity: automation.room4_hue_lights_time_of_evening_brightness_automatic
            - entity: automation.room4_sun_light_time_of_day_brightness_switch_on
            - entity: automation.room4_sun_light_time_of_evening_brightness_automatic
            - entity: automation.room_4_light
            - entity: automation.room_4_sun_off
            - entity: automation.room_4_sun_off_detected
            - entity: automation.room_4_sun_on
            - entity: automation.room_4_sun_on_detected
            - entity: automation.room_4_sun_toggle
            - entity: automation.room_4_venti_off
            - entity: automation.room_4_venti_on
            - entity: automation.shower_music_pause
            - entity: automation.shower_music_play
            - entity: automation.shower_showering_detected
            - entity: automation.shower_showering_finished
            - entity: automation.update_available_notification
            - entity: automation.weekday_sunrise
            - entity: automation.weekend_sunrise
            - entity: automation.ya_enter_home_notification
            - entity: automation.ya_leave_home_notification
          show_header_toggle: false
          title: All Automations
          type: Entities
        filter:
          include:
            - domain: automation
        type: 'custom:monster-card'
    icon: 'mdi:settings'
    path: settings
    title: Settings
  - badges: []
    cards:
      - entity: camera.monbijou
        show_header_toggle: false
        title: camera_monbijou
        type: picture-entity
      - entity: camera.baerenplatz
        show_header_toggle: false
        title: camera_baerenplatz
        type: picture-entity
      - entity: camera.alpen
        show_header_toggle: false
        title: camera_alpen
        type: picture-entity
      - entity: camera.gurten
        show_header_toggle: false
        title: camera_gurten
        type: picture-entity
      - entity: camera.muri
        show_header_toggle: false
        title: camera_muri
        type: picture-entity
      - entity: camera.grauholz
        show_header_toggle: false
        title: camera_grauholz
        type: picture-entity
      - entity: camera.villeneuve
        show_header_toggle: false
        title: camera_villeneuve
        type: picture-entity
      - entity: camera.thun
        show_header_toggle: false
        title: camera_thun
        type: picture-entity
      - entity: camera.spiez
        show_header_toggle: false
        title: camera_spiez
        type: picture-entity
      - entity: camera.niesen
        show_header_toggle: false
        title: camera_niesen
        type: picture-entity
      - entity: camera.luzern
        show_header_toggle: false
        title: camera_luzern
        type: picture-entity
      - entity: camera.tenero
        show_header_toggle: false
        title: camera_tenero
        type: picture-entity
    icon: 'mdi:image-multiple'
    path: cameras
    title: cameras
  - badges:
      - sensor.internet_roundtrip
      - sensor.homeassistant_version_newest
    cards:
      - entities:
          - entity: device_tracker.room4_phone_tinu
          - entity: device_tracker.room1_phone_ya
          - entity: device_tracker.room6_phone_neala
          - entity: sensor.room1_phone_ya_last_home
          - entity: sensor.room4_phone_tinu_last_home
          - entity: sensor.room6_phone_neala_last_home
        show_header_toggle: false
        title: Status
        type: entities
      - entities:
          - entity: sensor.date
          - entity: sensor.time
          - entity: sensor.last_boot
          - entity: sensor.disk_use_percent
          - entity: sensor.disk_free
          - entity: sensor.load_1m
          - entity: sensor.load_5m
          - entity: sensor.load_15m
        show_header_toggle: false
        title: System Status
        type: entities
      - entities:
          - sensor.fritz_netmonitor
        show_header_toggle: false
        title: Network Status
        type: entities
      - entities:
          - entity: device_tracker.pc19216817825
          - entity: device_tracker.guest_liu
        show_header_toggle: false
        title: Guests
        type: entities
    icon: 'mdi:message-settings'
    path: system
    title: system

