- alias: 'Studio Heizung einschalten'
  initial_state: true
  hide_entity: false
  trigger:
    platform: time
    minutes: '/5'
    seconds: 00
  condition:
    - condition: time
      after: '05:59:00'
      before: '22:00:00'
    - condition: template
      value_template: "{{ states.sensor.studio_temperature.state|float < 20 }}"
    - condition: or
      conditions:
        - condition: template
          value_template: "{{ is_state('sensor.automation_preset', 'home') }}"
        - condition: template
          value_template: "{{ is_state('sensor.automation_preset', 'sleep') }}"
        - condition: template
          value_template: "{{ is_state('sensor.automation_preset', 'guest') }}"
  action:
    service: switch.turn_on
    data:
      entity_id: switch.studio_heizung 

- alias: 'Studio Heizung ausschalten'
  initial_state: true
  hide_entity: false
  trigger:
    platform: time
    minutes: '/5'
    seconds: 00
  condition:
    - condition: template
      value_template: "{{ states.sensor.studio_temperature.state|float > 20 }}"
  action:
    service: switch.turn_off
    data:
      entity_id: switch.studio_heizung

