- alias: 'Studio Heizung einschalten'
  initial_state: true
  hide_entity: false
  trigger:
    platform: numeric_state
    entity_id: sensor.studio_temperature
    below: 20
  condition:
    condition: and
    conditions: 
      - condition: template
        value_template: "{{ is_state('sensor.automation_preset', 'home') }}"
      - condition: template
        value_template: "{{ is_state('device_tracker.galaxynotehome', 'home') }}"
  action:
    service: switch.turn_on
    data:
      entity_id: switch.studio_heizung 

- alias: 'Studio Heizung ausschalten'
  initial_state: true
  hide_entity: false
  trigger:
    platform: numeric_state
    entity_id: sensor.studio_temperature
    above: 20.1
  action:
    service: switch.turn_off
    data:
      entity_id: switch.studio_heizung

